### ISSUE TITLE
Migrate all configuration.xml files to a single yaml

### ISSUE THREAD

**Issue by porduna** [weblabdeusto/weblabdeusto#87]
It could be something like the following:

```yaml
  config:
    - global_config.py
    - global_config2.py
  instances:
    core_instance1:
      servers:
        core:
          config: [server_config_core1.py, server_config_core2.py]
    core_instance2:
      servers:
        core: {config: server_config_core2.py}
    core_instance3:
      servers:
        core: {config: server_config_core3.py}
    fpga1_box:
      servers:
        fpga:
          config: server_config_fpga.py
          protocols:
            xmlrpc: {port: 123}
    laboratory_instance:
      servers:
        lab:
          config: server_config_lab.py
          protocols:
              # Esto mola mas de lo que pensaba
            http: {port: "10002"}
        visir01: {config: server_config_lab.py}
        visir02: {config: server_config_lab.py}
        visir03: {config: server_config_lab.py}
  ```

**Comment by porduna** [comment]
It actually makes more sense to use config_file: [server_config_core1.py], and also support config: for variables. Most of the time, the core server will have only 2-3 variables, such as:

```yaml
 config_files:
    - global_config.py
    - global_config2.py
  instances:
    core_instance1:
      servers:
        core:
          config:
             core_coordinator_clean: true
             core_facade_port: 10000
             core_facade_server_route: 'route1'
    core_instance2:
      servers:
        core:
          config:
             core_facade_port: 10001
             core_facade_server_route: 'route2'
    core_instance3:
      servers:
        core:
          config:
             core_facade_port: 10002
             core_facade_server_route: 'route3'
    fpga1_box:
      servers:
        fpga:
          config_file: server_config_fpga.py
          protocols:
            xmlrpc: {port: 123}
    laboratory_instance:
      servers:
        lab:
          config_files: server_config_lab.py
          protocols:
              # Esto mola mas de lo que pensaba
            http: {port: "10002"}
        visir01: {config_files: server_config_lab.py}
        visir02: {config_files: server_config_lab.py}
        visir03: {config_files: server_config_lab.py}
```

**Comment by porduna** [comment]
Looking in more detail, @zstars and me figured out the following format:

```yaml

config_file: global_config.py
hosts:
  main:
    host: 192.168.0.80
    processes:
      process1:
        components: [core]
        config:
          core_coordinator_clean: true
          core_facade_port: 10000
          core_facade_server_route: 'route1'
      process2:
        components: [core]
        config:
          core_facade_port: 10001
          core_facade_server_route: 'route1'
      process3:
        components: [core]
        config:
          core_facade_port: 10002
          core_facade_server_route: 'route1'
      lab_process:
        components:
          general_laboratory:
            protocols:
              port: 1235
              http: {}
            config_file: lab/lab_config.py
            type: laboratory

          robot_experiment:
            protocols:
              bind: '127.0.0.1'
              port: 1234
              xmlrpc: {}
            type: experiment
            impl: experiments.robot_proglist.RobotProglist

```
